sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jorgemcunha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jorgemcunha/react-test npm test

after_sucess:
  - docker build -t jorgemcunha/multi-client ./client
  - docker build -t jorgemcunha/multi-nginx ./nginx
  - docker build -t jorgemcunha/multi-server ./server
  - docker build -t jorgemcunha/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
  - docker push jorgemcunha/multi-client
  - docker push jorgemcunha/multi-nginx
  - docker push jorgemcunha/multi-server
  - docker push jorgemcunha/multi-worker